/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/posts/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 게시글 상세 조회 */
        get: operations["get"];
        /**
         * 게시글 수정
         * @description 작성자 본인의 게시글을 수정합니다.
         */
        put: operations["update"];
        post?: never;
        /**
         * 게시글 삭제
         * @description 작성자 본인의 게시글과 연결된 미디어를 삭제합니다.
         */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 게시글 작성
         * @description 로그인 회원이 커뮤니티에 게시글을 작성하고 현재 가격 스냅샷을 저장합니다.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/reposts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 게시글 재게시 */
        post: operations["repost"];
        /** 게시글 재게시 취소 */
        delete: operations["unrepost"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 게시글 좋아요 */
        post: operations["like"];
        /** 게시글 좋아요 취소 */
        delete: operations["unlike"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 게시글 댓글 목록 조회 */
        get: operations["list"];
        put?: never;
        /**
         * 댓글 작성
         * @description 로그인 회원이 게시글에 댓글을 작성합니다.
         */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/posts/{postId}/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 게시글 북마크 */
        post: operations["bookmark"];
        /** 게시글 북마크 취소 */
        delete: operations["unbookmark"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{memberId}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 회원 팔로우 */
        post: operations["follow"];
        /** 회원 팔로우 취소 */
        delete: operations["unfollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 미디어 업로드
         * @description 로그인 회원이 게시글에 사용할 이미지 또는 영상을 업로드합니다.
         */
        post: operations["upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지갑 연결
         * @description 서명을 검증해 EVM 지갑 소유권을 확인하고 로그인 계정에 연결합니다.
         */
        post: operations["connect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/wallet/nonce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 지갑 연결 nonce 발급
         * @description 지갑 서명에 사용할 일회성 메시지와 nonce 식별자를 발급합니다.
         */
        post: operations["nonce"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 회원가입
         * @description 로그인 아이디로 회원을 생성하고 access token과 refresh cookie를 발급합니다.
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 인증 토큰 갱신
         * @description refresh cookie를 검증하고 access token과 refresh cookie를 재발급합니다.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그아웃
         * @description refresh token을 폐기하고 refresh cookie를 만료시킵니다.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 로그인
         * @description 로그인 아이디와 비밀번호를 검증하고 새로운 인증 토큰을 발급합니다.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 프로필 조회 */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 내 프로필 수정
         * @description 닉네임과 아바타 색상을 변경합니다.
         */
        patch: operations["update_1"];
        trace?: never;
    };
    "/api/v1/me/asset-visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 자산 공개 범위 변경 */
        patch: operations["visibility"];
        trace?: never;
    };
    "/api/v1/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 댓글 삭제
         * @description 작성자 본인의 댓글을 삭제합니다.
         */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        /**
         * 댓글 수정
         * @description 작성자 본인의 댓글 내용을 수정합니다.
         */
        patch: operations["update_2"];
        trace?: never;
    };
    "/api/v1/members/{memberId}/social": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 회원 팔로우 통계 조회
         * @description 팔로워·팔로잉 수와 로그인 회원의 팔로우 여부를 반환합니다.
         */
        get: operations["stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{memberId}/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회원 팔로잉 목록 조회 */
        get: operations["following"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/members/{memberId}/followers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 회원 팔로워 목록 조회 */
        get: operations["followers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/media/{fileName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 미디어 파일 조회 */
        get: operations["get_1"];
        put?: never;
        post?: never;
        /**
         * 미디어 파일 삭제
         * @description 업로드한 회원이 아직 게시글에 연결되지 않은 파일을 삭제합니다.
         */
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/wallets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 연결된 EVM 지갑 목록 조회 */
        get: operations["wallets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/bookmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 내 북마크 목록 조회 */
        get: operations["bookmarks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 내 자산 조회 및 갱신
         * @description 연결된 지갑의 블록체인 잔액과 현재 KRW 시세를 조회해 자산 스냅샷을 갱신합니다.
         */
        get: operations["assets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 전체 코인 실시간 시세 조회
         * @description 모든 활성 코인의 현재 가격과 24시간 등락률을 지정 통화로 반환합니다.
         */
        get: operations["current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/prices/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 코인 실시간 시세 조회
         * @description 코인 심볼에 해당하는 현재 가격과 24시간 등락률을 지정 통화로 반환합니다.
         */
        get: operations["current_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 전체 피드 조회
         * @description 커서 기반으로 전체 활동 피드를 조회합니다.
         */
        get: operations["feed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed/following": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 팔로잉 피드 조회
         * @description 로그인 회원이 팔로우한 회원의 게시글을 커서 기반으로 조회합니다.
         */
        get: operations["followingFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 코인 커뮤니티 정보 조회
         * @description 코인 기본 정보, 게시글 수와 커뮤니티 설명을 반환합니다.
         */
        get: operations["community"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/communities/{symbol}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 커뮤니티 게시글 목록 조회
         * @description 코인 커뮤니티의 게시글을 최신순으로 조회합니다.
         */
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 지원 코인 목록 조회
         * @description 현재 활성화된 코인을 화면 표시 순서대로 반환합니다.
         */
        get: operations["coins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/wallets/{walletId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * EVM 지갑 연결 해제
         * @description 과거 게시글과 댓글의 발행 스냅샷은 유지됩니다.
         */
        delete: operations["disconnect"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MediaRequest: {
            /** @enum {string} */
            type?: "IMAGE" | "VIDEO";
            url: string;
            thumbnailUrl?: string;
        };
        UpdatePostRequest: {
            title: string;
            content: string;
            media?: components["schemas"]["MediaRequest"][];
            tradingViewSymbol?: string;
            tradingViewInterval?: string;
            tradingViewAnalysis?: string;
            assetPrice?: number;
            assetPriceCurrency?: string;
            youtubeUrl?: string;
        };
        AuthorResponse: {
            /** Format: int64 */
            id?: number;
            nickname?: string;
            avatarColor?: string;
        };
        HolderSnapshotResponse: {
            verificationAvailability?: string;
            verificationLevel?: string;
            verifiedHolder?: boolean;
            quantityBand?: string;
            /** Format: int32 */
            holdingMonths?: number;
            /** Format: int32 */
            walletCount?: number;
            /** Format: date-time */
            capturedAt?: string;
            /** Format: int64 */
            blockNumber?: number;
            syncStatus?: string;
        };
        MediaResponse: {
            /** Format: int64 */
            id?: number;
            type?: string;
            url?: string;
            thumbnailUrl?: string;
            /** Format: int32 */
            order?: number;
        };
        PostResponse: {
            /** Format: int64 */
            id?: number;
            coinSymbol?: string;
            title?: string;
            content?: string;
            author?: components["schemas"]["AuthorResponse"];
            verifiedHolder?: boolean;
            assetValueKrw?: number;
            assetDisplay?: string;
            /** Format: int64 */
            likes?: number;
            /** Format: int64 */
            comments?: number;
            liked?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            media?: components["schemas"]["MediaResponse"][];
            tradingView?: components["schemas"]["TradingViewResponse"];
            priceSnapshot?: components["schemas"]["PriceSnapshotResponse"];
            youtube?: components["schemas"]["YoutubeResponse"];
            /** Format: int64 */
            reposts?: number;
            reposted?: boolean;
            bookmarked?: boolean;
            holderSnapshot?: components["schemas"]["HolderSnapshotResponse"];
        };
        PriceSnapshotResponse: {
            price?: number;
            currency?: string;
            /** Format: date-time */
            capturedAt?: string;
            source?: string;
        };
        TradingViewResponse: {
            symbol?: string;
            interval?: string;
            analysis?: string;
        };
        YoutubeResponse: {
            url?: string;
            videoId?: string;
            thumbnailUrl?: string;
        };
        CreatePostRequest: {
            coinSymbol: string;
            title: string;
            content: string;
            media?: components["schemas"]["MediaRequest"][];
            tradingViewSymbol?: string;
            tradingViewInterval?: string;
            tradingViewAnalysis?: string;
            assetPrice?: number;
            assetPriceCurrency?: string;
            youtubeUrl?: string;
        };
        CreateCommentRequest: {
            content: string;
        };
        CommentResponse: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            memberId?: number;
            nickname?: string;
            avatarColor?: string;
            content?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            holderSnapshot?: components["schemas"]["HolderSnapshotResponse"];
        };
        FollowStats: {
            /** Format: int64 */
            memberId?: number;
            /** Format: int64 */
            followers?: number;
            /** Format: int64 */
            following?: number;
            followedByMe?: boolean;
        };
        StoredMedia: {
            mediaType?: string;
            url?: string;
            contentType?: string;
            /** Format: int64 */
            size?: number;
        };
        WalletLoginRequest: {
            walletAddress: string;
            /** Format: uuid */
            nonceId: string;
            signature: string;
        };
        MemberResponse: {
            /** Format: int64 */
            id?: number;
            nickname?: string;
            avatarColor?: string;
            walletAddress?: string;
            assetVisibility?: string;
        };
        NonceRequest: {
            walletAddress: string;
        };
        NonceResponse: {
            /** Format: uuid */
            nonceId?: string;
            message?: string;
            /** Format: int64 */
            expiresInSeconds?: number;
        };
        SignupRequest: {
            loginId: string;
            password: string;
            nickname: string;
        };
        AuthResponse: {
            accessToken?: string;
            tokenType?: string;
            member?: components["schemas"]["MemberResponse"];
        };
        LoginRequest: {
            loginId: string;
            password: string;
        };
        UpdateMemberRequest: {
            nickname?: string;
            avatarColor?: string;
        };
        VisibilityRequest: {
            /** @enum {string} */
            visibility: "EXACT" | "RANGE" | "HIDDEN";
        };
        UpdateCommentRequest: {
            content: string;
        };
        MemberSummary: {
            /** Format: int64 */
            id?: number;
            nickname?: string;
            avatarColor?: string;
        };
        WalletResponse: {
            /** Format: int64 */
            id?: number;
            chainType?: string;
            address?: string;
            /** Format: date-time */
            connectedAt?: string;
        };
        AssetPortfolioResponse: {
            /** Format: int32 */
            walletCount?: number;
            assets?: components["schemas"]["AssetResponse"][];
        };
        AssetResponse: {
            symbol?: string;
            quantity?: number;
            valueKrw?: number;
            quantityBand?: string;
            verified?: boolean;
            verificationLevel?: string;
            status?: string;
            /** Format: int32 */
            walletCount?: number;
            /** Format: date-time */
            holdingSince?: string;
            /** Format: int32 */
            holdingMonths?: number;
            /** Format: date-time */
            capturedAt?: string;
            /** Format: int64 */
            blockNumber?: number;
            syncStatus?: string;
        };
        PriceQuote: {
            symbol?: string;
            price?: number;
            currency?: string;
            change24h?: number;
            /** Format: date-time */
            capturedAt?: string;
            source?: string;
        };
        FeedItemResponse: {
            eventType?: string;
            /** Format: date-time */
            occurredAt?: string;
            actor?: components["schemas"]["AuthorResponse"];
            post?: components["schemas"]["PostResponse"];
        };
        FeedPageResponse: {
            items?: components["schemas"]["FeedItemResponse"][];
            nextCursor?: string;
            hasMore?: boolean;
        };
        CoinResponse: {
            /** Format: int64 */
            id?: number;
            symbol?: string;
            name?: string;
            chainType?: string;
            accentColor?: string;
            verificationAvailability?: string;
            /** Format: int64 */
            chainId?: number;
            assetType?: string;
        };
        CommunityResponse: {
            coin?: components["schemas"]["CoinResponse"];
            /** Format: int64 */
            postCount?: number;
            description?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePostRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    repost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    unrepost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    like: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    unlike: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommentResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommentResponse"];
                };
            };
        };
    };
    bookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    unbookmark: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                postId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostResponse"];
                };
            };
        };
    };
    follow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FollowStats"];
                };
            };
        };
    };
    unfollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FollowStats"];
                };
            };
        };
    };
    upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StoredMedia"];
                };
            };
        };
    };
    connect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WalletLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberResponse"];
                };
            };
        };
    };
    nonce: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NonceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["NonceResponse"];
                };
            };
        };
    };
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberResponse"];
                };
            };
        };
    };
    visibility: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VisibilityRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommentResponse"];
                };
            };
        };
    };
    stats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FollowStats"];
                };
            };
        };
    };
    following: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberSummary"][];
                };
            };
        };
    };
    followers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                memberId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MemberSummary"][];
                };
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fileName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    wallets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WalletResponse"][];
                };
            };
        };
    };
    bookmarks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostResponse"][];
                };
            };
        };
    };
    assets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AssetPortfolioResponse"];
                };
            };
        };
    };
    current: {
        parameters: {
            query?: {
                currency?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceQuote"][];
                };
            };
        };
    };
    current_1: {
        parameters: {
            query?: {
                currency?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceQuote"];
                };
            };
        };
    };
    feed: {
        parameters: {
            query?: {
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedPageResponse"];
                };
            };
        };
    };
    followingFeed: {
        parameters: {
            query?: {
                cursor?: string;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FeedPageResponse"];
                };
            };
        };
    };
    community: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CommunityResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                size?: number;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PostResponse"][];
                };
            };
        };
    };
    coins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CoinResponse"][];
                };
            };
        };
    };
    disconnect: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                walletId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
